# DAT210x - Programming with Python for DS

## Module2 - Lab5

Import and alias Pandas:

In [1]:
# .. your code here ..
import pandas as pd

As per usual, load up the specified dataset, setting appropriate header labels.

In [2]:
# .. your code here ..
df = pd.read_csv('E:\Python_SYY\edx\DAT210x\Module2\Datasets\census.data',header = None)
df = df.drop(0,axis = 1)
df.reset_index(drop = True)
df.columns = ['education', 'age', 'capital-gain', 'race', 'capital-loss', 'hours-per-week', 'sex', 'classification']

Excellent.

Now, use basic pandas commands to look through the dataset. Get a feel for it before proceeding!

Do the data-types of each column reflect the values you see when you look through the data using a text editor / spread sheet program? If you see `object` where you expect to see `int32` or `float64`, that is a good indicator that there might be a string or missing value or erroneous value in the column.

In [3]:
# .. your code here ..
df['capital-gain'] = pd.to_numeric(df['capital-gain'],errors = 'coerce')

Try use `your_data_frame['your_column'].unique()` or equally, `your_data_frame.your_column.unique()` to see the unique values of each column and identify the rogue values.

If you find any value that should be properly encoded to NaNs, you can convert them either using the `na_values` parameter when loading the dataframe. Or alternatively, use one of the other methods discussed in the reading.

In [4]:
# .. your code here ..
#见上一个框

Look through your data and identify any potential categorical features. Ensure you properly encode any ordinal and nominal types using the methods discussed in the chapter.

Be careful! Some features can be represented as either categorical or continuous (numerical). If you ever get confused, think to yourself what makes more sense generally---to represent such features with a continuous numeric type... or a series of categories?

In [5]:
# .. your code here ..
df.education.unique()
ordered_education = ['Preschool','1st-4th', '5th-6th','7th-8th','9th','10th','11th','12th','HS-grad','Bachelors','Doctorate']
df.education = df.education.astype("category",ordered=True,categories=ordered_education).cat.codes
ordered_classification = ['<=50K','>50K']
df.classification = df.classification.astype("category",ordered=True,categories=ordered_classification).cat.codes
df2 = pd.get_dummies(df,columns=['race','sex'])

Lastly, print out your dataframe!

In [7]:
# .. your code here ..
df2

,education,age,capital-gain,capital-loss,hours-per-week,classification,race_Amer-Indian-Eskimo,race_Asian-Pac-Islander,race_Black,race_Other,race_White,sex_Female,sex_Male
0,9,39,2174.0,0,40,0,0,0,0,0,1,0,1
1,9,50,NaN,0,13,0,0,0,0,0,1,0,1
2,8,38,NaN,0,40,0,0,0,0,0,1,0,1
3,6,53,NaN,0,40,0,0,0,1,0,0,0,1
4,9,28,0.0,0,40,0,0,0,1,0,0,1,0
5,-1,37,0.0,0,40,0,0,0,0,0,1,1,0
6,4,49,0.0,0,16,0,0,0,1,0,0,1,0
7,8,52,0.0,0,45,1,0,0,0,0,1,0,1
8,-1,31,14084.0,0,50,1,0,0,0,0,1,1,0
9,9,42,5178.0,0,40,1,0,0,0,0,1,0,1
10,-1,37,0.0,0,80,1,0,0,1,0,0,0,1
11,9,30,0.0,0,40,1,0,1,0,0,0,0,1
12,9,23,0.0,0,30,0,0,0,0,0,1,1,0
13,3,34,0.0,0,45,0,1,0,0,0,0,0,1
14,8,25,0.0,0,35,0,0,0,0,0,1,0,1
15,8,32,0.0,0,40,0,0,0,0,0,1,0,1
16,6,38,0.0,0,50,0,0,0,0,0,1,0,1
17,-1,43,0.0,0,45,1,0,0,0,0,1,1,0
18,10,40,0.0,0,60,1,0,0,0,0,1,0,1
19,8,54,0.0,0,20,0,0,0,1,0,0,1,0
20,4,35,0.0,0,40,0,0,0,1,0,0,0,1
21,6,43,0.0,2042,40,0,0,0,0,0,1,0,1
22,8,59,0.0,0,40,0,0,0,0,0,1,1,0
23,9,56,0.0,0,40,1,0,0,0,0,1,0,1
24,8,19,0.0,0,40,0,0,0,0,0,1,0,1
25,-1,54,0.0,0,60,1,0,1,0,0,0,0,1
26,8,39,0.0,0,80,0,0,0,0,0,1,0,1
27,8,49,0.0,0,40,0,0,0,0,0,1,0,1
28,-1,20,0.0,0,44,0,0,0,1,0,0,0,1
29,9,45,0.0,1408,40,0,0,0,0,0,1,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
29506,8,30,0.0,0,55,0,0,0,0,0,1,0,1
29507,5,32,0.0,0,40,0,0,0,0,0,1,0,1
29508,-1,22,0.0,0,40,0,0,0,0,0,1,0,1
29509,8,31,0.0,0,40,0,0,0,0,0,1,1,0
29510,8,29,0.0,0,35,0,0,0,0,0,1,1,0
29511,9,35,0.0,0,55,1,0,0,0,0,1,1,0
29512,9,30,0.0,0,99,0,0,1,0,0,0,1,0
29513,10,34,0.0,0,60,1,0,0,0,0,1,0,1
29514,9,54,0.0,0,50,1,0,1,0,0,0,0,1
29515,-1,37,0.0,0,39,0,0,0,0,0,1,1,0
29516,7,22,0.0,0,35,0,0,0,1,0,0,0,1
29517,9,34,0.0,0,55,1,0,0,0,0,1,1,0
29518,8,30,0.0,0,46,0,0,0,1,0,0,0,1
29519,9,38,15020.0,0,45,1,0,0,1,0,0,1,0
29520,10,71,0.0,0,10,1,0,0,0,0,1,0,1
29521,8,45,0.0,0,40,0,0,0,0,0,1,1,0
29522,8,41,0.0,0,32,0,0,0,1,0,0,1,0
29523,8,72,0.0,0,25,0,0,0,0,0,1,0,1
29524,-1,31,0.0,0,30,0,0,0,0,1,0,1,0
29525,8,43,0.0,0,40,0,0,0,0,0,1,0,1
29526,-1,43,0.0,0,40,0,0,0,0,0,1,1,0
29527,-1,43,0.0,0,50,0,0,0,0,0,1,0,1
29528,5,32,0.0,0,40,0,1,0,0,0,0,0,1
29529,-1,32,0.0,0,11,0,0,1,0,0,0,0,1
29530,-1,53,0.0,0,40,1,0,0,0,0,1,0,1
29531,-1,22,0.0,0,40,0,0,0,0,0,1,0,1
29532,8,40,0.0,0,40,1,0,0,0,0,1,0,1
29533,8,58,0.0,0,40,0,0,0,0,0,1,1,0
29534,8,22,0.0,0,20,0,0,0,0,0,1,0,1
29535,8,52,15024.0,0,40,1,0,0,0,0,1,1,0